### ISSUE TITLE
Support for Varargs

### ISSUE THREAD

**Issue by mehalter** [Roger-luo/Comonicon.jl#26]
A lot of times when I make a command line tool using Julia, I like to have the ability to provide arbitrary number of arguments such as

`rm [options] [flags] args...` deletes ever argument in `args`
`mkdir [options] [flags] args...` makes all the directories listed in `args`

Currently when I try to do this, I get an invalid syntax for command line entry: `arg::String...`

Could this be extended to support variable argument lengths?

**Comment by Roger-luo** [comment]
True, this is useful indeed. The reason why I didn't support varargs was mainly because the codegen currently expands the splatting for optional arguments currently, e.g if you have `foo(x, y=1, z=2)`, this will be expanded to something like

```julia
foo(ARGS[1])
if n_args == 2
  foo(ARGS[1], ARGS[2])
end

if n_args == 3
  foo(ARGS[1], ARGS[2], ARGS[3])
end
```

and the `Arg` object does contains meta info about `vararg`, I think I'll put a meta info about whether an `Arg` is a varargs.

**Comment by Roger-luo** [comment]
cloased by #27
