### ISSUE TITLE
Ability to add a default set of options

### ISSUE THREAD

**Issue by mehalter** [Roger-luo/Comonicon.jl#45]
I think a nice feature would be the ability to add a default set of options for a given program, maybe in the form of an `@default` macro?

Consider the use case where you want to display the output of `-h` if someone runs the command with no parameters or arguments, you might be able to write something like `@default -h`. Not sure what the best design decision here would be.

**Comment by Roger-luo** [comment]
The problem is `-h` and `-V` is handled as a very special case. The program will scan `ARGS` and then give a signal to the codegen context. https://github.com/Roger-luo/Comonicon.jl/blob/master/src/codegen/ast.jl#L104 

I think in the context of Comonicon, we only transpile a Julia function to a shell function, which means it has to be compatible with Julia's own semantic. `@default` option will not be compatible with Julia's own semantic, which makes things less Julian and more Shellish.

I think all the options currently since they are treated as Julia kwargs, are enabled by default. 

> Consider the use case where you want to display the output of -h if someone runs the command with no parameters or arguments, you might be able to write something like @default -h. Not sure what the best design decision here would be.

This can be just handled as a special case, it was the way how version 0.3 handle error msgs, but as a result, this won't throw a quite long error msg (at least for IonCLI). We could consider bringing it back.

**Comment by Roger-luo** [comment]
I think as a workaround based on Julia's own semantic, one can always implement this behaviour as a default value of function arguments or kwargs.
