### ISSUE TITLE
Cleaner exit on invalid arguments

### ISSUE THREAD

**Issue by mehalter** [Roger-luo/Comonicon.jl#46]
If I have a command that takes specific flags with certain arguments, a normal behavior in terminal applications is to display the help dialog on an incorrect input. Say my command, `test`, only takes `-i <arg>` or `-q`, if I type in `test -i` or `test -m`, it would be nice for it to fail nicer than a stacktrace of the juilia code and print something like `Invalid arguments`, output of `test -h`, and return an exit code of 1 to the terminal.

**Comment by Roger-luo** [comment]
I think this is in dup of #45 

I think I'll just bring back the old behaviour shortly.

**Comment by Roger-luo** [comment]
I think after thinking about this a bit more, I'd like to keep the current Julia error msg. The reason is if the program terminates directly using `exit(1)`, it causes problems when one debugging the CLI program or embed this CLI package's entry in another Julia package/program (e.g if we use a deamon mode to execute commands in backend). This will terminates other programs unexpected since we are not using Julia's error handling tools.

**Comment by Roger-luo** [comment]
actually I just figured out the correct way to handle this, I missed an `exit` on the entry. Now it will print the help msg in 0a4133dd106523588c7732686794a7329a2cb9bd
