### ISSUE TITLE
A list of arguments?

### ISSUE THREAD

**Issue by xukai92** [Roger-luo/Comonicon.jl#47]
I want to support an unknown number of parameters, but below doesn't seem to work:
```julia
@cast function f(xs::Int...)
    ...
end
```

Neither does this
```julia
@cast function f(xs::Vector{Int})
    ...
end
```

What's the correct way to achieve what I want?

**Comment by mehalter** [comment]
Hm, I thought that this unknown number of parameters was fixed. It looks like IonCLI is doing this with a very strange syntax of

`@cast function f(x::Int, xs::Int...)` and then immediately doing `join([x, xs], " ")`

https://github.com/Roger-luo/IonCLI.jl/blob/d68eb1e06cb78a6b3a4b36d5b015e447826ce73b/src/project.jl#L43

I am using varargs in VirtualEnv.jl here (https://github.com/mehalter/VirtualEnv.jl/blob/03690e3db23c2428e52978350d1836e988081731/src/VirtualEnv.jl#L136) but I am not utilizing the `@cast` function since it just has an `@main` function, so I am unsure if there is a bug outside of that.

@Roger-luo is there a reason that you are separating out the first `pkg` from the other `pkgs` in IonCLI for the varags support?

**Comment by xukai92** [comment]
I think there is potentially a bug.

- `@cast function f1(args...)` works but `eltype(args)` is String
- `@cast function f2(args::String...)` also works
- `@cast function f3(args::Int...)` fails with `MethodError: no method matching f3(::String, ::String, ::String)`

**Comment by Roger-luo** [comment]
Yes, this is indeed a bug. Should be fixed in #50 

@mehalter It's not special syntax, `add` requires at least one argument.

**Comment by Roger-luo** [comment]
but now I think I should check that inside the function since as a result that will cause help to print extra things.

**Comment by xukai92** [comment]
Thanks!
