### ISSUE TITLE
-V and --version appear to be broken

### ISSUE THREAD

**Issue by mehalter** [Roger-luo/Comonicon.jl#49]
Whenever I run the `-V` or `--version` command I never get a version number. All it prints out is the command name. Also, it prints the name of the casted function instead of the name of the executable as specified by the user when installing.

**Comment by Roger-luo** [comment]
this is because if the version is v0.0.0 then it will not print any version. 
https://github.com/Roger-luo/Comonicon.jl/blob/master/src/types.jl#L230

this is because when you use it in a script, you won't want to print a version, and semantic versioning will ask one to set the version to v0.1.0 for the first version. I think there might be something wrong in getting your Project.toml's version info, then it sets the version to be v0.0.0

**Comment by mehalter** [comment]
Here is the repo with the code I am using: https://github.com/mehalter/VirtualEnv.jl/tree/comonicon

The version is set to `v0.2.0`

**Comment by Roger-luo** [comment]
this should be fixed by https://github.com/Roger-luo/Comonicon.jl/commit/601bb2505581cfa0bc15b06b18820cc1d797e9d8

**Comment by mehalter** [comment]
Awesome! It seems to be working now, thanks!
